# 결제 서비스 테스트용 설정파일
debug: false
management:
  endpoints:
    web:
      exposure:
        include:  "*"

logging:
  level:
    com.projectboard.boardproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.transaction: trace
    org.springframework.transaction.interceptor: trace
    org.springframework.jdbc.datasource: trace

spring:
  sql:
    init:
      mode: never
#      data-locations: classpath:sql/data-payment.sql
  flyway:
    enabled: true
    locations: classpath:db/migration/payment
  application:
    name: board-project
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: yjin0034
    password: bada332@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true

pg:
  url: https://c83cf442-fa9a-497e-b749-b34e2def113a.mock.pstmn.io/confirm # 포스트맨 mock 서버
