debug: false
management:
  endpoints:
    web:
      exposure:
        include:  "*"

logging:
  level:
    com.projectboard.boardproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.transaction: trace
    org.springframework.transaction.interceptor: trace
    org.springframework.jdbc.datasource: trace

spring:
  sql:
    init:
      mode: always
#      data-locations: classpath:sql/data-board.sql
  flyway:
    enabled: true
    locations: classpath:db/migration/board
  application:
    name: board-project
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: yjin0034
    password: bada332@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true
